# Generated by Django 5.2.6 on 2025-09-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_prettynum'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
        ),
    ]
