# Generated by Django 5.2.6 on 2025-10-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_orderinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(max_length=3, verbose_name='年龄')),
                ('avatar', models.CharField(max_length=128, verbose_name='头像')),
            ],
        ),
    ]
