# Generated by Django 5.2.6 on 2025-10-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(max_length=128, upload_to='avatar', verbose_name='头像'),
        ),
    ]
