"""empty message

Revision ID: 7349c6a7fa4a
Revises: 8c58b92240d5
Create Date: 2025-09-20 09:38:57.828446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7349c6a7fa4a'
down_revision = '8c58b92240d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_python_flask_email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('captcha', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_python_flask_email_captcha')
    # ### end Alembic commands ###
