"""empty message

Revision ID: 875499ea5195
Revises: 7349c6a7fa4a
Create Date: 2025-09-20 10:20:50.215527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875499ea5195'
down_revision = '7349c6a7fa4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_python_flask_email_captcha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_python_flask_email_captcha', schema=None) as batch_op:
        batch_op.drop_column('create_time')

    # ### end Alembic commands ###
